name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: 'Build job'
    runs-on: ubuntu-latest
    
    steps:
      
    - name: checkout repo
      uses: actions/checkout@v2.3.1
      
    - name: 'Azure WebApp deploy - publish profile with container'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ak-test-php
        publish-profile: ${{ secrets.PUBLISH_PROFILE_PHP }}
        package: .
        
