name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: 'Build job'
    runs-on: ubuntu-latest
    
    steps:
      
    - name: checkout repo
      uses: actions/checkout@v2.3.1
      
    - name: 'Az CLI login with subscription'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    - name: 'Azure WebApp deploy - php'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ak-test-php
        package: .
        
